### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by dmpossa** [junzis/pyModeS#152]
```
[sdr_usr@linux sdr]$ modeslive --source rtlsdr
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 2000000.052982 Hz
Traceback (most recent call last):
  File "/home/sdr_usr/.local/lib/python3.11/site-packages/pyModeS/extra/rtlreader.py", line 193, in run
    self._read_callback(data, None)
  File "/home/sdr_usr/.local/lib/python3.11/site-packages/pyModeS/extra/rtlreader.py", line 169, in _read_callback
    messages = self._process_buffer()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sdr_usr/.local/lib/python3.11/site-packages/pyModeS/extra/rtlreader.py", line 87, in _process_buffer
    threshold = max(frame_pulses) * 0.2
                ^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```

**Comment by junzis** [comment]
The buggy code path in `rtlreader.py` no longer exists in v3.0.0 — the entire RTL-SDR streaming module from v2 has been removed. RTL-SDR source support is tracked as a v3 follow-up (see the roadmap), and will be rebuilt without this class of issue. Closing as the original bug no longer applies.
