### ISSUE TITLE
Missing zmq package

### ISSUE THREAD

**Issue by maranov** [junzis/pyModeS#51]
Hi, since 2.3, the pyzmq is not "extras" anymore, since pyModeS can't be imported without it:
```
>>> from pyModeS import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "blah\env\lib\site-packages\pyModeS\__init__.py", line 13, in <module>
    from .extra import tcpclient
  File "blah\env\lib\site-packages\pyModeS\extra\tcpclient.py", line 9, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
```

It should probably be either moved to install_requires or the imports should be moved to function-level.

Thanks.

pyModeS 2.3 on Python 3.7.4, 64-bit, Windows.

**Comment by junzis** [comment]
Thanks for point this out. I pushed a new version (2.4) which fixed the imports.
