### ISSUE TITLE
Error in importing / Traceback (most recent calls last)

### ISSUE THREAD

**Issue by t-ctrl** [junzis/pyModeS#74]
calling modeslive --help gives the following erors

# modeslive --help
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/usr/local/bin/modeslive", line 12, in <module>
    from pyModeS.streamer.source import NetSource,RtlSdrSource
  File "/usr/local/lib/python3.6/dist-packages/pyModeS/streamer/source.py", line 3, in <module>
    from pyModeS.extra.rtlreader import RtlReader
  File "/usr/local/lib/python3.6/dist-packages/pyModeS/extra/rtlreader.py", line 4, in <module>
    from rtlsdr import RtlSdr
  File "/usr/local/lib/python3.6/dist-packages/rtlsdr/__init__.py", line 56, in <module>
    from .librtlsdr import librtlsdr
  File "/usr/local/lib/python3.6/dist-packages/rtlsdr/librtlsdr.py", line 61, in <module>
    f = librtlsdr.rtlsdr_get_device_count
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/bin/python3: undefined symbol: rtlsdr_get_device_count

**Comment by junzis** [comment]
I suspect this has something to do with the rtl-sdr library on your computer. 

Please try to reinstall `librtlsdr-dev` and `librtlsdr0` to see if it solves the problem.

**Comment by kastork** [comment]
not my ticket, but installing `librtlsdr` solved this sort of problem for me. (on a mac simply `brew install librtlsdr`)

I understand the need for this library for accessing the radio directly.  Don't know if it is possible, but It would be nice if this dependency wasn't necessary when accessing a dump1090 network stream from another device.

**Comment by junzis** [comment]
@kastork, good recommendation. This is considered now in the commit 7a4c465.
