### ISSUE TITLE
modeslive --hex2bin bug

### ISSUE THREAD

**Issue by sdradsb** [junzis/pyModeS#75]
modeslive --source rtlsdr
Traceback (most recent call last):
  File "/home/lal/.local/bin/modeslive", line 10, in <module>
    from pyModeS.streamer.decode import Decode
  File "/home/lal/.local/lib/python2.7/site-packages/pyModeS/__init__.py", line 8, in <module>
    from . import py_common as common
  File "/home/lal/.local/lib/python2.7/site-packages/pyModeS/py_common.py", line 7
    def hex2bin(hexstr: str) -> str:
                      ^
SyntaxError: invalid syntax

I am getting this while I try to run the "modeslive".

**Comment by junzis** [comment]
Python 2 is not supported. You need to update your Python to 3.6+.
